# Generated by Django 5.0.6 on 2024-05-17 11:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="shared_with",
            field=models.ManyToManyField(
                related_name="shared_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
