# Generated by Django 5.0.6 on 2024-05-17 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_notes_shared_with"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_notes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
