# Generated by Django 5.0.4 on 2024-05-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('School/Education', 'School/Education'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Recipes', 'Recipes'), ('Health/Fitness', 'Health/Fitness'), ('Finance', 'Finance'), ('Projects', 'Projects'), ('Ideas', 'Ideas')], default='Personal', max_length=20),
        ),
    ]
