# Generated by Django 5.0.4 on 2024-05-03 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('School/Education', 'School/Education'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Recipes', 'Recipes'), ('Health/Fitness', 'Health/Fitness'), ('Finance', 'Finance'), ('Projects', 'Projects'), ('Ideas', 'Ideas')], default='Personal', max_length=20)),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='notes.notes')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
