# Generated by Django 5.0.4 on 2024-05-03 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_notes_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='notes.category'),
        ),
    ]
