# Generated by Django 5.0.4 on 2024-05-03 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_category_notes_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.category'),
        ),
    ]
