# Generated by Django 5.1.7 on 2025-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_alter_notes_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="notes",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="notes", to="notes.tag"
            ),
        ),
    ]
