# Generated by Django 5.1.7 on 2026-02-16

from django.db import migrations, models

CATEGORY_CHOICES = [
    "Personal",
    "Work",
    "School/Education",
    "Shopping",
    "Travel",
    "Recipes",
    "Health/Fitness",
    "Finance",
    "Projects",
    "Ideas",
]


def create_default_categories(apps, schema_editor):
    Category = apps.get_model("notes", "Category")
    for name in CATEGORY_CHOICES:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_tag_notes_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="notes",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="notes",
                to="notes.category",
            ),
        ),
        migrations.RunPython(create_default_categories, migrations.RunPython.noop),
    ]
