# Generated by Django 5.0.4 on 2024-05-03 09:15

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('notes', 'Category')
    CATEGORY_CHOICES = [
        ('Personal', 'Personal'),
        ('Work', 'Work'),
        ('School/Education', 'School/Education'),
        ('Shopping', 'Shopping'),
        ('Travel', 'Travel'),
        ('Recipes', 'Recipes'),
        ('Health/Fitness', 'Health/Fitness'),
        ('Finance', 'Finance'),
        ('Projects', 'Projects'),
        ('Ideas', 'Ideas'),
    ]
    for category_name, _ in CATEGORY_CHOICES:
        Category.objects.create(name=category_name)

def reverse_func(apps, schema_editor):
    # This function is used to reverse this migration. 
    # It's not always possible to reverse a data migration, 
    # but in this case you can delete the Category objects you created.
    Category = apps.get_model('notes', 'Category')
    Category.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_category_alter_notes_category'),
    ]

    operations = [
        migrations.RunPython(create_categories, reverse_func),
    ]
