# Generated by Django 5.1.7 on 2026-02-16

import json
from django.db import migrations, models


def convert_quill_to_html(apps, schema_editor):
    Notes = apps.get_model("notes", "Notes")
    for note in Notes.objects.exclude(text__isnull=True):
        raw_value = (note.text or "").strip()
        if not raw_value:
            continue
        if raw_value.startswith("{"):
            try:
                data = json.loads(raw_value)
            except json.JSONDecodeError:
                continue
            if isinstance(data, dict):
                html = data.get("html")
                if html is not None:
                    note.text = html
                    note.save(update_fields=["text"])


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_categories_cleanup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="text",
            field=models.TextField(),
        ),
        migrations.RunPython(convert_quill_to_html, migrations.RunPython.noop),
    ]
