# Generated by Django 5.0.4 on 2024-05-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_notes_share_with'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='share_with',
            new_name='shared_with',
        ),
    ]
