# Generated by Django 5.1.7 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_presence_and_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
